version: '3.9'

services:
  postgresql:
    build: ./postgres
    container_name: postgresql
    ports:
      - 5432:5432
    # env_file: .env.db
  
  splunk:
    build: ./splunk
    container_name: splunk
    ports:
      - 8000:8000
    depends_on: 
      - postgresql