port: 9999
driversFolder: ${SPLUNK_HOME}/etc/apps/splunk_app_db_connect/drivers/
logbackConfigurationFile: ${SPLUNK_HOME}/etc/apps/splunk_app_db_connect/config/command_logback.xml
maxParalleQuery: 200
